### ISSUE TITLE
单元测试的时候，有时通过，有时不通过

### ISSUE THREAD

**Issue by brucenan** [qiniu/ip17mon-java#7]
单元测试中执行了find（ip）的函数调用，但是有时可以正常解析，有时又报下面的错误：
`java.lang.ArrayIndexOutOfBoundsException: -1111494912
	at qiniu.ip17mon.Locator.findIndexOffset(Locator.java:270)
	at qiniu.ip17mon.Locator.find(Locator.java:294)
	at qiniu.ip17mon.Locator.find(Locator.java:284)`

完全不知道为啥.

**Comment by longbai** [comment]
谢谢，我看下
